# Generated by Django 4.1.1 on 2022-11-11 14:28

from django.db import migrations, models
import django.db.models.deletion
import images.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCompleto', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('username', models.CharField(max_length=50, verbose_name='Nome de Usuário')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('password', models.CharField(max_length=50, verbose_name='Senha')),
            ],
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Imagem')),
                ('image', models.ImageField(upload_to=images.models.upload_to, verbose_name='Imagem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.user', verbose_name='Usuário')),
            ],
        ),
    ]
