# Generated by Django 3.0.8 on 2022-11-07 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageupload',
            old_name='usr',
            new_name='user',
        ),
    ]
