# Generated by Django 3.0.8 on 2022-11-04 12:03

from django.db import migrations, models
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=usuarios.models.upload_image_user),
        ),
    ]
